### ISSUE TITLE
Idea about concent

### ISSUE THREAD

**Issue by ricemann** [GDPRWP/standard#10]
I think I am going to use the interface for my solutions. So Here is some basic idea of mine:

Users do have to permit our data handling with their consent. Typically with the use of a checkbox and it is just an addition to what we normally have of consent checkboxes.

But, how about giving users the ability to take back concent, and at the same time, you could disable the user. And delete data after some safe period of time. Or giving the user some feedback about how long data will be kept and why.

**Comment by ePascalC** [comment]
First of all a comment on the "it's just an addition" if I may: It's a bit more then that  ;-)
The transparency part of the GDPR indicates that as admin or data controller, we have the duty to seek the data subject’s consent by means of a clear affirmative act and the ability to demonstrate that the consent has been obtained. This should be done in clear and plain language and not be just 'another box to tick'.

But you are correct in saying that a user needs to have the possibility to withdraw the consent. If indeed certain data still needs to be maintained, this will have to be clarified!

**Comment by ricemann** [comment]
@ePascalC Thank you for your feedback - yes you are right. It should be clear in the flow that the consent is for personal data. And actually, we could think about a standard instead of a checkbox - maybe some text field where they provide their full name or something.

**Comment by dejliglama** [comment]
Hi Thomas - @ricemann, nice to see you in here ;)

For now, the interface is focused on finding identifying  PII (Personal Identifiable Information) across plugins in an installation. And with that, also request the data to be anonymized. 

The issue of concent is that it should be given much more fine grained than that of the past, and in it self a field we need to keep track of. - for now, it's out of scope of the curent version of the interface, and might be a thing that isn't going to be in the interface itself, but rather something offered by a plugin based on the data available via the interface implementations in installed plugins. 

A withdrawal of a concent should of course mean that the anonymize mechanism of the interface is triggered. For now, it's a "delete" all, thing but could be on specific fields of data in the future.

We do intend for you to be able to provide a TTL on each data field, so you give us a sense of the duration of a piece of information is expected to live.  Some sort of automatic anonymizing could happen based on this.

**Comment by dejliglama** [comment]
I hope it's OK I close this discussion to keep track of where I've been. Catch me on slack if you disagree, and I will open it again :)

**Comment by ricemann** [comment]
Hi @dejliglama,

It is totally fine - and really a good project this one - I will stay tuned : ) Actually I have to figure out how to handle GDPR. A lot is going to need this and time is ticking.

I like the idea of figuring out how to handle all needs - by defining an interface. 

I will get back if I have some more ideas : ) Chears : )
