### ISSUE TITLE
What license is this code licensed under?

### ISSUE THREAD

**Issue by ntwb** [GDPRWP/standard#14]
What license is this code licensed under?

Once known, please add said license 😄

**Comment by dejliglama** [comment]
The idéa would be to license it under GPL http://www.gnu.org/licenses/gpl-3.0.txt

**Comment by ntwb** [comment]
Thanks @dejliglama, can you please include the license in the repo, this GitHub License wizard will add the license to the repo: https://github.com/GDPRWP/PHP-interface/community/license/new?branch=master

p.s. I'd be more inclined and would prefer  to go with https://www.gnu.org/licenses/gpl-2.0.html which is what WP itself uses

**Comment by dejliglama** [comment]
Will do Stephen thanks!
________________________________
