### ISSUE TITLE
forget_user_() - filter to select which user data will be forgotten

### ISSUE THREAD

**Issue by vyskoczilova** [GDPRWP/standard#8]
Hi guys, great initiative and I would love to help with testing later :). Have you thought about a filter/function which could set up which data will be forgotten and which not? For example - if I have a shop - I need to store info about the purchase as long as I need to for guarantee, invoicing etc. But there can be other user data (preferences, additional info etc.) which could be deleted as the user request. Do you plan to add that kind of filter over the data control (it can vary among countries, I guess) and if can't be deleted to add an "error" message, why it has to be still stored?

**Comment by ePascalC** [comment]
Basic principle is that data should be kept only as long as really needed. So removing part of the data stored might not only be based on a request of the user, but could also come from the tool.

So something to delete some of the data in a more granular way, yes please ! :-)

**Comment by dejliglama** [comment]
Yes we've thought in these lines. 

To be clear, any deleting / anonymizing of data is to be done by the plugin developer, we only put the function in place that they need to use. How deleting is done is up to each plugin dev.

We DO however plan to let you specify for how long, each piece of data is needed. So for each field you mark as holding PII, you can also provide a TTL (Time to Live). We aren't going to delete based on this, but it will be something we can show a website admin, in order for them to be compliant and consitent with their own system.
